import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class JobService {

  constructor( private http: HttpClient) { }

  getJobs(): Observable<TopLevel[]>{
    return this.http.get<TopLevel[]>('https://localhost:7047/api/Jobs/GetJobs');
  }
}

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface TopLevel {
  codJob:                    number;
  jobName:                   string;
  jobDescription:            string;
  codDepartamento:           number;
  codCiudad:                 number;
  location:                  string;
  companyName:               CompanyName;
  codCategory:               number;
  codJobStatus:              number;
  publish:                   boolean;
  createdDate:               string;
  createdUser:               EdUser;
  modifiedDate:              null | string;
  modifiedUser:              EdUser | null;
  jobShortDescription:       string;
  isVisible:                 boolean;
  jobSchedule:               string;
  jobAmount:                 null | string;
  jobTime:                   null | string;
  startTime:                 null | string;
  endTime:                   null | string;
  sortOrder:                 number | null;
  codCategoryNavigation:     null;
  codCiudadNavigation:       null;
  codDepartamentoNavigation: null;
  codJobStatusNavigation:    null;
  traineeAditionalDocs:      any[];
  traineesXjobs:             any[];
}

export enum CompanyName {
  Cit = "CIT",
  CompanyNameCit = "Cit",
  CreativeInformationTechnologiesCIT = "Creative Information Technologies (CIT)",
  DichterNeira = "Dichter Neira",
}

export enum EdUser {
  Admin = "admin",
}

